NAME	=	i_do_not_want_to_set_the_world_on_fire

SRCS	=	main.cpp		\
			Animal.cpp		\
			Cat.cpp			\
			Dog.cpp			\
			WrongAnimal.cpp	\
			WrongCat.cpp	\
			Brain.cpp

INCS	=	Animal.hpp		\
			Cat.hpp			\
			Dog.hpp			\
			WrongAnimal.hpp	\
			Brain.hpp 
			
include ../template.mk
