NAME	=	interface_and_recap

SRCS	=	main.cpp			\
			AMateria.cpp		\
			Character.cpp		\
			Cure.cpp			\
			Ice.cpp				\
			MateriaSource.cpp

INCS	=	AMateria.hpp		\
			Character.hpp		\
			Cure.hpp			\
			ICharacter.hpp		\
			IMateriaSource.hpp	\
			Ice.hpp				\
			MateriaSource.hpp	

include ../template.mk
